name: DoubleLife
version: '${project.version}'
main: de.cooperr.doublelife.DoubleLife
api-version: 1.19
authors: [ Cooperr06 ]
description: Double Life Plugin for our 3rd Minecraft Server

commands:
  sendlife:
    description: Sende Leben an andere Spieler
    usage: /sendlife <target>
